import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getMcpCatalogEntry } from "@squadrons/shared";
import type { EnabledPluginRuntime } from "./store.js";

const HOST_DIR = path.dirname(fileURLToPath(import.meta.url));
/** Monorepo packages/squadrons-backtest/mcp-server.mjs */
const BACKTEST_MCP_SERVER = path.resolve(
  HOST_DIR,
  "../../../../packages/squadrons-backtest/mcp-server.mjs",
);

const MCP_CLIENT = "@deepseek-ai/dsh-mcp-client";

/** Env var prefix for injected plugin secrets (never written into YAML as plaintext). */
export function pluginSecretEnvName(pluginId: string, secretKey: string): string {
  const safeId = pluginId.replace(/[^A-Za-z0-9]/g, "").slice(0, 24);
  const safeKey = secretKey.replace(/[^A-Za-z0-9_]/g, "_").toUpperCase();
  return `SQUADRONS_MCP_${safeId}_${safeKey}`;
}

export type McpPatchResult = {
  /** Absolute path to agent-local Cordis patch, or null when no plugins. */
  patchPath: string | null;
  /** Env vars to merge into the dsh child (secret values). */
  env: Record<string, string>;
};

/**
 * Build a Cordis overlay for per-agent plugins.
 * - First-party Backtest is always bundled in the sdk profile; we disable it
 *   per-agent when Plugins → Backtest is off.
 * - Remote catalog/custom plugins use dsh-mcp-client rows.
 */
export async function buildAgentMcpPatch(
  workspace: string,
  plugins: EnabledPluginRuntime[],
): Promise<McpPatchResult> {
  const env: Record<string, string> = {};
  const rows: string[] = [];

  const backtestEnabled = plugins.some(
    (plugin) => plugin.catalogId === "backtest",
  );
  if (!backtestEnabled) {
    rows.push(["- id: squadrons-backtest", "  disabled: true"].join("\n"));
  }

  for (const plugin of plugins) {
    if (plugin.catalogId === "backtest") continue;
    const built = buildPluginRow(plugin, env);
    if (built) rows.push(built);
  }

  if (rows.length === 0) {
    return { patchPath: null, env: {} };
  }

  const dir = path.join(workspace, ".squadrons");
  await mkdir(dir, { recursive: true });
  const patchPath = path.join(dir, "mcp.cordis.yml");
  const yaml = [
    "# Generated by Squadrons — per-agent MCP plugins. Do not edit by hand.",
    ...rows,
    "",
  ].join("\n");
  await writeFile(patchPath, yaml, "utf8");
  return { patchPath, env };
}

function buildPluginRow(
  plugin: EnabledPluginRuntime,
  env: Record<string, string>,
): string | null {
  const cordisId = `mcp-${plugin.serverName}`;

  if (plugin.kind === "catalog" && plugin.catalogId) {
    const entry = getMcpCatalogEntry(plugin.catalogId);
    if (!entry) return null;

    if (entry.transport === "streamable-http" && entry.url) {
      const headerLines: string[] = [];
      for (const [hk, hv] of Object.entries(entry.headers ?? {})) {
        headerLines.push(`      ${yamlKey(hk)}: ${yamlString(hv)}`);
      }
      for (const spec of entry.secrets) {
        if (!spec.headerName) continue;
        const value = plugin.secrets[spec.key];
        if (!value) continue;
        const envName = pluginSecretEnvName(plugin.id, spec.key);
        env[envName] = value;
        headerLines.push(
          `      ${yamlKey(spec.headerName)}: !!js process.env.${envName}`,
        );
      }
      return [
        `- id: ${cordisId}`,
        `  name: ${yamlString(MCP_CLIENT)}`,
        `  config:`,
        `    serverName: ${yamlString(entry.serverName)}`,
        `    transport: streamable-http`,
        `    url: ${yamlString(entry.url)}`,
        ...(headerLines.length > 0
          ? [`    headers:`, ...headerLines]
          : []),
        `    failOnStartupError: false`,
      ].join("\n");
    }

    if (entry.transport === "stdio" && entry.command) {
      // First-party Backtest is bundled + disabled above — never MCP stdio.
      if (entry.id === "backtest") return null;

      const envLines: string[] = [];
      for (const spec of entry.secrets) {
        const value = plugin.secrets[spec.key];
        if (!value) continue;
        const envName = pluginSecretEnvName(plugin.id, spec.key);
        env[envName] = value;
        const childEnv = spec.envName ?? spec.key;
        envLines.push(
          `      ${yamlKey(childEnv)}: !!js process.env.${envName}`,
        );
      }
      const resolved = resolveCatalogStdio(entry.id, entry.command, entry.args);
      return [
        `- id: ${cordisId}`,
        `  name: ${yamlString(MCP_CLIENT)}`,
        `  config:`,
        `    serverName: ${yamlString(entry.serverName)}`,
        `    transport: stdio`,
        `    command: ${yamlString(resolved.command)}`,
        `    args: ${JSON.stringify(resolved.args)}`,
        ...(envLines.length > 0 ? [`    env:`, ...envLines] : []),
        `    failOnStartupError: false`,
      ].join("\n");
    }
    return null;
  }

  // Custom
  const config = plugin.config;
  if (!config) return null;

  if (config.transport === "streamable-http" && config.url) {
    const headerLines: string[] = [];
    for (const [secretKey, headerName] of Object.entries(
      config.headerSecretKeys ?? {},
    )) {
      const value = plugin.secrets[secretKey];
      if (!value) continue;
      const envName = pluginSecretEnvName(plugin.id, secretKey);
      env[envName] = value;
      headerLines.push(
        `      ${yamlKey(headerName)}: !!js process.env.${envName}`,
      );
    }
    return [
      `- id: ${cordisId}`,
      `  name: ${yamlString(MCP_CLIENT)}`,
      `  config:`,
      `    serverName: ${yamlString(plugin.serverName)}`,
      `    transport: streamable-http`,
      `    url: ${yamlString(config.url)}`,
      ...(headerLines.length > 0 ? [`    headers:`, ...headerLines] : []),
      `    failOnStartupError: false`,
    ].join("\n");
  }

  if (config.transport === "stdio" && config.command) {
    const envLines: string[] = [];
    for (const [secretKey, childEnv] of Object.entries(
      config.envSecretKeys ?? {},
    )) {
      const value = plugin.secrets[secretKey];
      if (!value) continue;
      const envName = pluginSecretEnvName(plugin.id, secretKey);
      env[envName] = value;
      envLines.push(
        `      ${yamlKey(childEnv)}: !!js process.env.${envName}`,
      );
    }
    // Also inject any leftover secrets by their key name
    for (const [secretKey, value] of Object.entries(plugin.secrets)) {
      if (config.envSecretKeys?.[secretKey]) continue;
      const envName = pluginSecretEnvName(plugin.id, secretKey);
      env[envName] = value;
      envLines.push(
        `      ${yamlKey(secretKey)}: !!js process.env.${envName}`,
      );
    }
    const args = config.args ?? [];
    return [
      `- id: ${cordisId}`,
      `  name: ${yamlString(MCP_CLIENT)}`,
      `  config:`,
      `    serverName: ${yamlString(plugin.serverName)}`,
      `    transport: stdio`,
      `    command: ${yamlString(config.command)}`,
      `    args: ${JSON.stringify(args)}`,
      ...(envLines.length > 0 ? [`    env:`, ...envLines] : []),
      `    failOnStartupError: false`,
    ].join("\n");
  }

  return null;
}

/** First-party stdio plugins resolve to absolute node paths in the monorepo. */
function resolveCatalogStdio(
  catalogId: string,
  command: string,
  args: string[] | undefined,
): { command: string; args: string[] } {
  if (catalogId === "backtest") {
    return {
      command: process.execPath,
      args: [BACKTEST_MCP_SERVER],
    };
  }
  return { command, args: args ?? [] };
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function yamlKey(key: string): string {
  // Quote keys that aren't plain identifiers (e.g. NANSEN-API-KEY, x-dune-api-key)
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) return key;
  return JSON.stringify(key);
}
